feat(sessions):pagination-api-pilotage
SocialGouv/pass-emploi-api pull request #1204
Opened 2023-09-01 09:15 UTC by walidOcto

2023-09-15 12:39 UTC, arthurlbrjc requested changes

2023-09-15 12:39 UTC, arthurlbrjc commented on src/application/queries/query-getters/milo/v2/get-sessions-conseiller.milo.v2.query.getter.db.ts
> +      return success(sessionsQueryModels.filter(filtrerSessionAClore))
Faut faire le filtre avant de calculer le nombre de pages et tout.

2023-09-15 12:39 UTC, arthurlbrjc commented on src/application/queries/query-getters/milo/v2/get-sessions-conseiller.milo.v2.query.getter.db.ts
> +        sessions.push(...resultMiloClientParPage.data.sessions)
Pourquoi on récupère TOUTES les sessions de milo ? Pour reconstruitre la pagination nous-même ?  
Est-ce qu'il "suffit" pas de faire un petit calcul pour transposer leur pagination vers la leur ?  
Par exemple
> on veut notre page 3 (sessions 30 à 39), c'est dans la page 1 de milo (sessions 0 à 49)
> on veut notre page 7 (sessions 70 à 79), c'est dans la page 2 de milo (session 50 à 59)

```ts
const facteurTranspositionPages = nbSessionsParPageMilo / nbSessionsParPageApi
const pageMilo = Math.ceil(pageApi / facteurTranspositionPages)
// .... récupération sessionsMilo
const pageApiDansPageMilo = pageApi % facteurTranspositionPages
const sessionsPageApi = sessionsPageMilo.slice(nbSessionsParPageApi * (pageApiDansPageMilo - 1), nbSessionsParPageApi * pageApiDansPageMilo)
```
Un truc comme ça.

2023-09-15 12:39 UTC, arthurlbrjc commented on src/infrastructure/routes/validation/conseiller-milo.inputs.ts
> +export class GetSessionsV2QueryParams {
Le but d'une v2 c'est de remplacer à terme la v1, donc d'être utilisé au même endroit.  
Du coup il faut que ça réponde au moins au même besoin.  
Donc il faut que ça gère `dateDebut` et `dateFin`

2023-09-15 12:39 UTC, arthurlbrjc commented on src/application/queries/query-getters/milo/v2/get-sessions-conseiller.milo.v2.query.getter.db.ts
> +        sessions.push(...resultMiloClientParPage.data.sessions)
Aaaaah, mais on est peut-être obligé d'en récupérer plus que nécessaire à cause du filtre `filtrerAClore` que Milo ne gère pas :thinking:  
Faut peut-être faire un truc smart, genre récupérer 50 sessions, vérifier si on en a assez _à clore_ pour remplir une page API, sinon en récupérer 50 de plus, etc... (et du coup ça vaut peut-être le coup de séparer le code en 2 query-getters, `GetSessionsStructurePaginees` et `GetSessionsStructureAClorePaginees`)

2023-09-15 12:39 UTC, arthurlbrjc commented on src/infrastructure/routes/conseillers.milo.controller.ts
> +    private readonly getSessionsV2QueryHandler: GetSessionsConseillerMiloV2QueryHandler,
À supprimer d'ici.

2023-09-18 13:39 UTC, arthurlbrjc commented on src/application/queries/query-getters/milo/v2/get-sessions-conseiller.milo.v2.query.getter.db.ts
> +        const sessionSqlModel = sessionsSqlModels.find(
Plutôt que de faire un `find` qui va reparcourir toute la liste à chaque fois, on pourrait construire une `Map<string, SessionSqlModel>` qui indexe les sessions par leur id ?

2023-09-18 15:16 UTC, Mzem commented on src/application/queries/milo/v2/get-sessions-conseiller.milo.v2.query.handler.db.ts
> +export class GetSessionsConseillerMiloV2QueryHandler extends QueryHandler<
plutot GetSessionsACloreDuConseillerMilo

2023-09-19 13:42 UTC, walidOcto commented on src/infrastructure/routes/validation/conseiller-milo.inputs.ts
> +export class GetSessionsV2QueryParams {
dans la mesure ou c'est pas utiliser on se met en mode YAGNI ? pour ne pas mettre en place de chose qu'on de va pas utiliser ?  a faire evoluer en fonction du besoin

2023-09-19 13:43 UTC, walidOcto commented on src/infrastructure/routes/v2/conseillers.milo.controller.v2.ts
> +@Controller('v2/conseillers/milo')
c'est ce qui est deja present sur d'autre routes, on en a discuter avec arthur et on est tomber d'accord sur ca pour le moment , on peut reflechir a une autre solution a l'occasion . pas fermer a la discussion

2023-09-19 13:44 UTC, walidOcto commented on src/application/queries/milo/v2/get-sessions-conseiller.milo.v2.query.handler.db.ts
> +export class GetSessionsConseillerMiloV2QueryHandler extends QueryHandler<
non car la notion de "aClore" est gerer par le filtre on peut aussi recuperer des sessions qui ne sont pas a clore

2023-09-19 14:56 UTC, arthurlbrjc approved these changes

2023-09-19 14:58 UTC, merged