feat(sessions-milo): refacto filtres inscription pour sessions du jeune
SocialGouv/pass-emploi-api pull request #1216
Opened 2023-09-06 14:32 UTC by Mzem

2023-09-06 16:18 UTC, adgeg commented on src/application/queries/get-jeune-home-agenda.query.handler.db.ts
> +          filtrerEstInscrit: true
Donc là on est dans l'agenda du jeune, vu par le jeune OU le conseiller, c'est bien ça ?
Du coup, le `filtrerEstInscrit` à `true`, on est bons pour les 2 publics ?

2023-09-06 16:22 UTC, adgeg commented on src/application/queries/query-getters/milo/get-sessions-jeune.milo.query.getter.db.ts
> +  switch (filtreInscription) {
On sent l'influence du Pattern Matching Dart de @chapuyj !!!

2023-09-06 16:27 UTC, adgeg commented on test/application/queries/query-getters/milo/get-sessions-jeune.milo.query.getter.db.test.ts
> +    describe("quand c'est un conseiller", () => {
Erreur de votre part ce test tout commenté ?

2023-09-06 16:28 UTC, adgeg requested changes
Je mets un request changes juste pour les tests. A moins que vous me disiez la raison du pourquoi du gros commentaire :)

2023-09-06 16:56 UTC, adgeg approved these changes

2023-09-06 17:08 UTC, Mzem commented on src/application/queries/get-jeune-home-agenda.query.handler.db.ts
> +          filtrerEstInscrit: true
yes exactement

2023-09-06 17:09 UTC, adgeg commented on src/application/queries/get-jeune-home-agenda.query.handler.db.ts
> +          filtrerEstInscrit: true
top !

2023-09-07 07:54 UTC, arthurlbrjc requested changes

2023-09-07 07:54 UTC, arthurlbrjc commented on src/infrastructure/clients/dto/milo.dto.ts
> +export enum StatutInscriptionMilo {
Faut arrêter avec les enum sur des valeurs qu'on maîtrise pas :)
C'est pour ça qu'on avait fait les `const MILO_INSCRIT, MILO_REFUS_TIERS, MILO_REFUS_JEUNE, MILO_PRESENT`

2023-09-07 07:57 UTC, Mzem commented on src/infrastructure/clients/dto/milo.dto.ts
> +export enum StatutInscriptionMilo {
je ne voulais pas baser la logique de ma query sur une comparaison de strings

2023-09-07 08:20 UTC, arthurlbrjc approved these changes

2023-09-07 08:41 UTC, merged