feat/ajout-date-creation-table-rendez-vous
SocialGouv/pass-emploi-api pull request #1247
Opened 2023-09-26 13:53 UTC by walidOcto

2023-09-26 14:49 UTC, Mzem commented on src/infrastructure/sequelize/migrations/20230926134516-ajout-date-creation-table-rendez-vous.js
> +      defaultValue: Sequelize.fn('now')
c trompeur vaut mieux laisser nullable

2023-09-27 09:42 UTC, Mzem requested changes
default à now c trompeur vaut mieux laisser nullable

2023-09-27 10:00 UTC, oni-Sk commented on src/infrastructure/sequelize/migrations/20230926134516-ajout-date-creation-table-rendez-vous.js
> +      defaultValue: Sequelize.fn('now')
Yes allowNull : true. Pas de default value

2023-09-28 08:31 UTC, Mzem commented on src/domain/rendez-vous/rendez-vous.ts
> +        dateCreation: new Date()
manque sql model

2023-10-03 12:29 UTC, walidOcto commented on src/infrastructure/sequelize/migrations/20230926134516-ajout-date-creation-table-rendez-vous.js
> +      defaultValue: Sequelize.fn('now'),
c'est ce que je tesais jeudi matin a la journée en presentiel, ca pose probleme car ca va set tout les ancien RDV a la date du jour ( now )

2023-10-03 12:29 UTC, walidOcto commented on src/infrastructure/sequelize/migrations/20230926134516-ajout-date-creation-table-rendez-vous.js
> +      defaultValue: Sequelize.fn('now'),
testais **

2023-10-04 06:40 UTC, merged