feat(actions): qualif multiple
SocialGouv/pass-emploi-api pull request #1357
Opened 2024-01-11 11:54 UTC by Mzem

2024-01-11 14:36 UTC, oni-Sk requested changes
Pas de test du handler ?

2024-01-11 14:36 UTC, oni-Sk commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +    for (const action of actions) {
La boucle est très grande, on pourrait pas enjoliver rendre l'intention plus claire

2024-01-11 14:36 UTC, oni-Sk commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +          await this.conseillerAuthorizer.autoriserConseillerPourSonJeune(
On a un autoriserConseillerPourSesJeunes. On doit limiter les appels réseaux ça pourrait faire des command infernales sinon, chaque jeune et chaque action dans une requête sql individuelle c'est trop lourd

2024-01-11 14:42 UTC, Mzem commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +        this.actionRepository.get(qualification.idAction)
ça doit etre explicite que l'appel vers l'exterieur est unitaire

2024-01-11 14:42 UTC, Mzem commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +    _utilisateur: Authentification.Utilisateur,
oui sauf si on rend les paramètres du handler un objet

2024-01-11 14:44 UTC, Mzem commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +          await this.conseillerAuthorizer.autoriserConseillerPourSonJeune(
tout à fait

2024-01-12 08:56 UTC, oni-Sk reviewed
Attention à la perf dans le getAggregate + les AE à corriger + logger les erreurs.

Le handler est toujours compliqué mais je m'embarque pas dans ces retours là car ça ferait trop de modifs sur le repo et le domain qu'on a pas encore l'habitude de faire donc je pourrais pas te guider comme il faut. Si on a le temps de pair c'est l'occasion d'essayer par contre

2024-01-12 08:56 UTC, oni-Sk commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +      command.idsActions.map(idAction => this.actionRepository.get(idAction))
Tu peux toujours pas faire une get regroupé plutôt que faire une requête sql par action ?

2024-01-12 08:56 UTC, oni-Sk commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +        idsActionsEnErreur.push(idAction)
Est-ce qu'on enverrait pas un couple id action; type de l'erreur ou message d'erreur. Car je vois plus bas qu'on a plusieurs raisons différentes d'échouer

2024-01-12 08:56 UTC, oni-Sk commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +        idsActionsEnErreur.push(idAction)
NonTrouve plutôt du 404, QualificationCejEchouee, QualificationExterneMiloEchouee,  SaveEnBDDEchoue plutôt du 500 mais la 2e et la 4e sont inquiétantes alors que la 3e Milo externe on peut simplement dire de réessayer plus tard

2024-01-12 08:56 UTC, oni-Sk commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +
Logger les erreurs

2024-01-12 08:56 UTC, oni-Sk commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +        Evenement.Code.ACTION_QUALIFIEE_NON_SNP,
C'est pas les bons AE, il faut en faire des nouveaux pour la qualif multiple

2024-01-12 08:56 UTC, oni-Sk commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +        Evenement.Code.ACTION_QUALIFIEE_SNP,
kifkif

2024-01-12 09:15 UTC, Mzem commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +        Evenement.Code.ACTION_QUALIFIEE_SNP,
bien vu

2024-01-12 09:29 UTC, Mzem commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +        idsActionsEnErreur.push(idAction)
en fait on est pas du tout au clair sur la gestion des erreurs coté front, donc la on va pas différencier les cas d'erreurs car YAGNI
Une fois que le front voit plus clair, on réadaptera la classification des erreurs en fonction de son besoin

2024-01-12 09:29 UTC, Mzem commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +
ok pour des logs

2024-01-12 09:30 UTC, Mzem commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +
en fait c'est déjàa loggé dans les méthodes du repo

2024-01-12 09:34 UTC, Mzem commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +
je rajoute quand meme un petit log warn mais c'est pas très utile

2024-01-12 09:37 UTC, Mzem commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +      command.idsActions.map(idAction => this.actionRepository.get(idAction))
je peux, je fais ça

2024-01-12 09:42 UTC, arthurlbrjc requested changes

2024-01-12 09:42 UTC, arthurlbrjc commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +}
On peut juste renvoyer le tableau des actions en erreur nan ? Le web va pas utiliser autre chose je pense.

2024-01-12 09:42 UTC, arthurlbrjc commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +  commentaireQualification?: string
Ça pas de sens ça dans la qualification groupée

2024-01-12 09:42 UTC, arthurlbrjc commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +}
C'est pas bon. Chaque action a sa propre catégorie, son propre commentaire, ses propres dates, etc.
Et il manque la qualification en non SNP.
Je pense que comme cinématique on peut avoir un truc qui ressemble à ça :point_down:

Option 1 : on récupère la data dans l'API
```ts
type command = { idsActions: string[], snp: boolean }

const actions = getActions(command.idsActions)
command.idsActions.forEach((idAction) => {
  const action = actions.find(idAction)
  if (!action) { // erreur action pas trouvée }
  if (!action.dateFin) { // on ne peut psa qualifier, ajouter aux actions en erreur }

  if (!snp) { qualifierEnNonSNP() }
  
  if (!action.codeCategorie) { // on ne peut pas qualifier, ajouter aux actions en erreur }
  const qualif = {
    categorie: action.codeCategorie,
    commentaire: action.titre + ' - ' + action.description,
    dateDebut: action.dateCreation,
    dateFin: action.dateFin
  }
  qualifierEnSnp(qualif)
}
```

2024-01-12 09:42 UTC, arthurlbrjc commented on src/infrastructure/routes/actions.controller.ts
> +    deprecated: true,
C'est pas `deprecated` ça, on va toujours l'utiliser pour de la qualification unitaire.

2024-01-12 09:51 UTC, oni-Sk commented on src/infrastructure/routes/actions.controller.ts
> +    deprecated: true,
Je pensais qu'on pourrait faire la bascule plus tard pour alléger le code mais c'est une discussion pour plus tard

2024-01-12 09:52 UTC, Mzem commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +  commentaireQualification?: string
donc pas de commentaire dans la qualif groupéé ??

2024-01-12 10:06 UTC, arthurlbrjc commented on src/infrastructure/routes/actions.controller.ts
> +    deprecated: true,
Ils veulent garder la différenciation des événements d'engagement entre qualification "groupée" et "simple"

2024-01-12 10:52 UTC, arthurlbrjc commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +    dateFinReelle?: DateTime
En fait, l'API récupère déjà la `dateDebut = dateCreation` et la `dateFin = dateFinReelle`, et le web va pas les modifier. Donc pas besoin des dates dans le payload/la commande.

2024-01-12 10:52 UTC, arthurlbrjc commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +    commentaireQualification?: string
L'API build déjà le commentaire et le web va pas le modifier, donc pas besoin dans le payload/la commande.

2024-01-12 10:52 UTC, arthurlbrjc commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +      )
C'est peut-être plus claire si laisse la condition snp dans le corps du `handle` ?
```ts
if (actionQualifiee.qualification.code !== Qualification.Code.NON_SNP) {
  qualifierEnSNP()
}
```

2024-01-12 10:52 UTC, arthurlbrjc commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +    for (const action of actions) {
À confirmer avec le métier s'ils veulent un seul AE ou un par action :thinking:

2024-01-12 11:29 UTC, Mzem commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +      )
ok

2024-01-12 11:31 UTC, Mzem commented on src/application/commands/milo/qualifier-actions-milo.command.handler.ts
> +    for (const action of actions) {
tant que tu peux qualifier en multiple des actions qui sont des snp et d'autres pas snp je ne vois pas commenet on peut en avoir un seule AE
au pire ils nous feront un retour

2024-01-15 08:58 UTC, merged