Feature: us 32 offres emploi list
SocialGouv/pass-emploi-api pull request #59
Opened 2021-11-08 09:38 UTC by Mzem

2021-11-08 10:52 UTC, BonnetM requested changes
RC pour les quelques tests qui manquent (surtout ceux qui n'ont pas été mis à jour et qui pètent la CI)

2021-11-08 10:52 UTC, BonnetM commented on domain/offres_emploi/offres_emploi_repository.py
> +class OffresEmploiRepository(ABC):
Est-ce que les repositories n'auraient pas plutôt leur place dans le package `application` ? 🤔 

Si on découpe nos classes en `domain` et `application`, je trouve ça assez étrange d'avoir une notion de repository dans le `domain`

2021-11-08 10:52 UTC, BonnetM commented on domain/offres_emploi/offre_emploi.py
> +class OffreEmploi:
Du coup le but c'est de mettre à terme toutes les classes qui sont dans `model` ici ?

2021-11-08 10:52 UTC, BonnetM commented on application/use_cases/offres_emploi_use_case.py
> +class OffresEmploiUseCase:
Un peu la même question que sur le model, le but c'est à terme de bouger tous les use cases dans `application/use_cases` ?

2021-11-08 10:52 UTC, BonnetM commented on initialize_use_cases.py
> +offres_emploi_api_repository = OffresEmploiAPIRepository(offres_emploi_api_datasource)
Tout petit détail, mais la variable pourrait toujours s'appeler `offres_emploi_repository`

2021-11-08 10:52 UTC, BonnetM commented on application/use_cases/offres_emploi_use_case.py
> +        offres_emploi = self.offresEmploiRepository.get_offres_emploi(page, limit, search_term, departement)
Les TUs n'ont pas été mis à jour là-dessus (d'ailleurs ils ne sont pas passés sur la CI, sûrement à cause de ça)

2021-11-08 10:52 UTC, BonnetM commented on infrastructure/datasources/offres_emploi_api_datasource.py
> +def generate_query_param_range(page: int, limit: int):
Est-ce qu'on poserait pas quelques TUs sur cette méthode ?

2021-11-08 10:52 UTC, BonnetM commented on infrastructure/transformers/offres_emploi_transformer.py
> +def to_offres_emploi(offres_emploi_response: dict) -> List[OffreEmploi]:
Ca vaudrait le coup de poser des tests sur cette transformation ?

2021-11-08 11:11 UTC, arthurlbrjc commented on domain/offres_emploi/offres_emploi_repository.py
> +class OffresEmploiRepository(ABC):
Le domain doit savoir qu'il peut récupérer/sauvegarder des entités grace aux repo. Et ça change pas si jamais ton application ou ton infra change. C'est pour ça que ça que l'interface des repo ont leur place dans le domain.

2021-11-08 11:17 UTC, arthurlbrjc commented on domain/offres_emploi/offre_emploi.py
> +class OffreEmploi:
Peut-être que cette classe n'est pas encore tout à fait au bon endroit parce qu'elle ne porte aucune logique métier.  
Elle représente le format de sortie du use case (_QueryModel_) et aurait sa place putôt dans l'application à côté du use case. Pour l'instant on l'a mise ici parce que la distinction command/query et application/domain est pas hyper sèche.

2021-11-08 11:18 UTC, arthurlbrjc commented on application/use_cases/offres_emploi_use_case.py
> +class OffresEmploiUseCase:
En effet. Et même idéalement avec une distinction query/model.

2021-11-08 13:00 UTC, arthurlbrjc commented on initialize_use_cases.py
> +offres_emploi_api_repository = OffresEmploiAPIRepository(offres_emploi_api_datasource)
Pas forcément d'accord. On instancie ici explicitement un `api_repository`, on pourrait avoir ailleurs un `sql_repository`.

2021-11-08 14:29 UTC, BonnetM commented on domain/offres_emploi/offres_emploi_repository.py
> +class OffresEmploiRepository(ABC):
Ok je vois ! J'avais plus la vision que les objets métiers et leurs règles sont dans le domain et que c'est à l'appli de savoir si elle a besoin de les récup/sauvegarder.  

Mais franchement j'ai jamais trop travaillé avec un découpage si fin, donc si ça vous semble plus logique on peut laisser comme ça :)

2021-11-09 08:59 UTC, BonnetM approved these changes

2021-11-09 09:09 UTC, merged